services:

  db:
    build: ./mysql/
    volumes:
      - ./mysql/mysql_data:/var/lib/mysql         # perpetuation of data
      - ./mysql/sqls:/docker-entrypoint-initdb.d  # pushing initial data
      - ./mysql/logs:/var/log/mysql               # log record
    environment:
      - MYSQL_ROOT_PASSWORD=password
