services:
  front-app:
    build:
      context: .
    ports:
      - "9000:3000"
    volumes:
      - ./front-app:/app
      - node_modules:/app/node_modules
    command: sh -c "npm run dev"

volumes:
  node_modules: