version: "3"
services:
  app-plate:
    container_name: app-plate-go
    build:
      context: .
      dockerfile: ./build/Dockerfile
    volumes:
      - ./app-plate:/go/src/github.com/app-plate
    ports:
      - "5000:5000"
    tty: true
    env_file:
      - ./build/.go_env
    environment:
      - TZ=Asia/Tokyo
    command: sh -c "go run ./cmd/main.go"