import Head from 'next/head'
import { useState } from 'react';
import MemoDetailedView from './memoDetailedView';

export default function MemoView(): JSX.Element {
  const sampleMemoAry=[
    {
      title : "memo1",
      author: "user0",
      body: "this is body of memo1.\n and this is second line.",
      filepath: "./next.svg",
      id: 1,
      date: "2023-05-14",
      tags: [ "tagA", "tagB" ,"tagC"]
    },
    {
      title : "memo2",
      author: "user5",
      body: "this is body of memo2.\n and this is second line.\n and this is third line.",
      filepath: "",
      id: 2,
      date: "2023-06-1",
      tags: [ "tagB", "tagD" ,"tagC"]
    }
  ]

  const [readingMemo, setReadingMemo] = useState(0);
  
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* 3-column */}
      <div className="container-fluid">
        <div className="row vh-100 overflow-auto">
          <div className="col-2 h-100 border left-column overflow-auto">
          </div>
          <div className="center-column col-5 h-100 border overflow-auto">
            <MemoSelector handler={setReadingMemo} />
          </div>
          <div className="right-column col-5 h-100 border border-warning overflow-auto">
            <MemoDetailedView memo={sampleMemoAry[readingMemo]}/>
          </div>
        </div>
      </div>
    </>
  )
}

function MemoSelector({handler}:any): JSX.Element{ 
  return (
    <div className='memoSelector m-1'>
      <button type='button' className="btn btn-primary m-1" 
        onClick={()=>{ handler(0) }}>
        Memo1
      </button>
      <button type='button' className="btn btn-primary m-1"
        onClick={()=>{ handler(1) }}>
        Memo2
      </button>
    </div>
  );
}
